language: en

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "tokenizer_whitespace"
- name: "ner_synonyms"
- name: intent_featurizer_count_vectors
  token_pattern: (?u)\b\w+\b
- name: "intent_classifier_tensorflow_embedding"
